config/routes.rb
Rails.application.routes.draw do
 
  
  
  get 'users/index'
  devise_for :users, :path_prefix => 'id' ,
  :controllers => { :omniauth_callbacks => 
  "users/omniauth_callbacks" }

  
  resources :users, :only =>[:show]


  
  resources :tours do
      member do
        get 'join'
        delete :remove_from_tour
      end
    resources :stops
    resources :comments
    resources :memberships
  end
  #root 'tours#index'
  root 'tours#index'
  get 'home/index'
  get 'home/about'
  get 'home/stat'
  get 'home/ALL'
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  
  
  
  get 'invitations/create'
  get 'invitations/destroy'
  get 'invitations/update'

 

  
 
 
 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stop.rb
class Stop < ApplicationRecord
  belongs_to :tour
  validates :address, presence: true
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :get_tour
  before_action :set_stop, only: %i[ show edit update destroy ]
  before_action :authenticate_user!,except: [:home_about, :home_index, :home_stat]
  before_action :correct_user, only: [:edit, :update, :destroy]
 
  # GET /stops or /stops.json
  def index
    @stops = @tour.stops
    @hash = Gmaps4rails.build_markers(@stops) do |stop, marker|
      marker.lat stop.latitude
      marker.lng stop.longitude
    end
   
  end

  # GET /stops/1 or /stops/1.json
  def show
  end

  # GET /stops/new
  def new
    @stop = @tour.stops.build
  end

  # GET /stops/1/edit
  def edit
  end

  # POST /stops or /stops.json
  def create
    @stop = @tour.stops.build(stop_params)

    respond_to do |format|
      if @stop.save
        format.html { redirect_to tour_path(@tour), notice: "Stop was successfully created." }
        format.json { render :show, status: :created, location: @stop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stops/1 or /stops/1.json
  def update
    respond_to do |format|
      if @stop.update(stop_params)
        format.html { redirect_to tour_path(@tour), notice: "Stop was successfully updated." }
        format.json { render :show, status: :ok, location: @stop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stops/1 or /stops/1.json
  def destroy
    @stop.destroy
    respond_to do |format|
      format.html { redirect_to tour_path(@tour), notice: "Stop was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  
  private
    # Use callbacks to share common setup or constraints between actions.
    def get_tour
      @tour = Tour.find(params[:tour_id])
    end
    def set_stop
      @stop = @tour.stops.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stop_params
      params.require(:stop).permit(:postition, :address, :latitude, :longitude, :arrival_date, :tour_id)
    end
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/stops/_form.html.erb
<%= form_with(model: [@tour,stop],local: true, data: { controller: "places", action: "google-maps-callback@window->places#initMap", places_latitude: stop.latitude, places_longitude: stop.longitude }) do |form| %>
  <% if stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
        <% stop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="d-flex p-2">
<div class="p-4" >
  <div class="form-group">
    <%= form.label :postition %>
    <%= form.number_field :postition, class: 'form-control' %>
  </div>

 <div class="form-group">
    <%= form.label :address %>
    <%= form.search_field :address, class: 'form-control', data: { target: "places.field", action: "keydown->places#keydown" } %>
  </div>

  <div class="form-group">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, class: 'form-control', data: { target: "places.latitude" } %>
  </div>

  <div class="form-group">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, class: 'form-control', data: { target: "places.longitude" } %>
  </div>

  <div class="form-group">
    <%= form.label :arrival_date %>
    <%= form.date_select :arrival_date, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :Duration %>
    <%= form.text_field :duration, class: 'form-control' %>
  </div>
  <br>
  <div class="actions">
    <%=form.submit class:"btn btn-outline-primary" %>

  </div>
</div>
  <div class="p-4">
      <div data-target="places.map" style="height:400px;width:400px"></div>
    </div>
</div>

  
<% end %>

app/views/stops/edit.html.erb
<h1>Editing Stop</h1>

<%= render 'form', stop: @stop %>

<%= link_to 'Show', [@tour,@stop] %> |
<%= link_to 'Back', tour_stops_path(@tour) %>

app/views/stops/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4"><%= @tour.Autista %> <%= @tour.Partenza %>- <%= @tour.destinazione %></h1>
  <p class="lead"><p>
  <strong>Mezzo di trasporto:</strong>
  <%= @tour.Mezzo_Di_Trasporto %>
</p>

<p>
  <strong>Data:</strong>
  <%= @tour.Data %>
</p>
<p>
  <strong>Durata:</strong>
  <%= @tour.durata %>
</p>

<p>
  <strong>Posti disponibili:</strong>
  <%= @tour.Posti_Disponibili %>
</p>
<p>
  <strong>Partenza:</strong>
  <%= @tour.Partenza%>
</p>

<p>
  <strong>Destinazione:</strong>
  <%= @tour.destinazione %>
</p>










<h1>Stops</h1>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Postition</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Arrival date</th>
      <th>Tour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= stop.postition %></td>
        <td><%= stop.address %></td>
        <td><%= stop.latitude %></td>
        <td><%= stop.longitude %></td>
        <td><%= stop.arrival_date %></td>
        <td><%= stop.tour_id %></td>
        <%if @tour.user==current_user%>
        <td><%= link_to 'Show Stop', [@tour,stop] %></td>
        <td><%= link_to 'Edit Stop', edit_tour_stop_path(@tour,stop) %></td>
        <td><%= button_to 'Destroy Stop', [@tour,stop], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>


<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

      
<br>
<%= link_to 'Back', home_ALL_path,class:"btn btn-dark" %>

<%if @tour.user==current_user%>
<%= link_to 'New Stop', new_tour_stop_path(@tour) %>
<%end%>

app/views/stops/new.html.erb
<h1>New Stop</h1>

<%= render 'form', stop: @stop %>

app/views/stops/show.html.erb
<p id="notice"><%= notice %></p>

<main class="ui two column doubling stackable grid container">
    <div class="column">
        <div class="ui basic segment">
            <h1 class="display-4" class="ui header">
               <%= @stop.address %>
            </h1>
        </div>
        <div class="ui raised padded text segment">
            <h3>Latitude</h3>
            <p>
               <%= @stop.latitude %>
            </p>
            <h3>Longitude:</h3>
            <p>
               <%= @stop.longitude %>
            </p>
            <h3>Tempo</h3>
            <%= @stop.duration %>
            <p>
                
            </p><p>
            <%if @tour.user==current_user%>
    <%= link_to 'Edit', edit_tour_stop_path(@tour,@stop),class:"btn btn-outline-warning" %> 
            <%= button_to 'Destroy Stop', [@tour,@stop],class:"btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
    
  
  <% end %>
            
            </div>
            </div>
        <div class="column">
            <div class="ui basic segment"></div>
            
                <div class="ui segment">
                    <h3>Mappa:</h3>
                    <div style='width: 800px;'>
  <div id="map" style='width: 500px; height: 400px;'></div>
</div>

<script>
      
    handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
   markers = handler.addMarkers([
      {
          "lat": "<%= @stop.latitude %>",
          "lng": "<%= @stop.longitude %>",
          "infowindow": "<%= @stop.address %>"
          
      }  
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>


 </div>
 </div>
 

 </main>