config/routes.rb
Rails.application.routes.draw do
 
  
  
  get 'users/index'
  devise_for :users, :path_prefix => 'id' ,
  :controllers => { :omniauth_callbacks => 
  "users/omniauth_callbacks" }

  
  resources :users, :only =>[:show]


  
  resources :tours do
      member do
        get 'join'
        delete :remove_from_tour
      end
    resources :stops
    resources :comments
    resources :memberships
  end
  #root 'tours#index'
  root 'tours#index'
  get 'home/index'
  get 'home/about'
  get 'home/stat'
  get 'home/ALL'
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  
  
  
  get 'invitations/create'
  get 'invitations/destroy'
  get 'invitations/update'

 

  
 
 
 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  def stat
  end
  def ALL
  end
  
 
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/ALL.html.erb
<% if user_signed_in?%>








<h1>My Tours</h1> 
<div class="d-flex flex-row-reverse">
<%= link_to 'Aggiungi Tour', new_tour_path,class:"btn btn-outline-success" %>
</div>

<br>







<main class="ui two column doubling stackable grid container">
<section class="column">
<div class="container pb-5 mt-n2 mt-md-n3">
    <div class="row">
    <% Tour.all.each do |tour| %>
    <%if tour.user==current_user%>
        
            
            <!-- Item-->
            <!-- Item-->
            <!-- Item-->
            
            <div class="d-sm-flex justify-content-between my-4">
                <div class="media d-block d-sm-flex text-center text-sm-left">
                    <div class="cart-item-thumb mx-auto mr-sm-4">
                    <div class="account-settings">
                  <div class="card-body">
                  <div class="user-profile">
                  <div class="user-avatar" class= "img-circular">
                    <%=image_tag(tour.user.avatar_thumbnail) %>
                    </div>
                    <%= link_to 'Show Trip', tour,class:"btn btn-outline-primary" %>
                    </div>
                    </div>
                    </div>
                    
                    </div>
                    <div class="media-body pt-3">
                        <h3 class="product-card-title font-weight-semibold border-0 pb-0"><%= link_to  tour.user.username, user_path(tour.user) %></h3>
                        <div class="font-size-sm"><span class="text-muted mr-2">Start:</span>
                        <%= tour.Data %>|<%= tour.Partenza %></div>
                        <div class="font-size-sm"><span class="text-muted mr-2">End:</span>
                        <%= tour.enddate %>|<%= tour.destinazione %></div>
                        <div class="font-size-sm"><span class="text-muted mr-2">Descrizione:</span>
                        <%= tour.description %></div>
                        <div class="font-size-sm"><span class="text-muted mr-2">Veichle:</span><%= tour.Mezzo_Di_Trasporto %></div>
                        <div class="font-size-sm"><span class="text-muted mr-2">Passengers:</span>  <%tour.memberships.count%>/<%= tour.Posti_Disponibili %></div>
                    </div>
                </div>
                <div class="pt-2 pt-sm-0 pl-sm-3 mx-auto mx-sm-0 text-center text-sm-left" style="max-width: 10rem;">
                    
                          <div class="pt-2 pt-sm-0 pl-sm-4 mx-auto mx-sm-0 text-center text-sm-left" style="max-width: 10rem;">
                          <div class="form-group mb-2">
                          <br>
                          <td><%= link_to 'Modifica', edit_tour_path(tour),class:'btn btn-outline-warning ' %></td>
                          <br>
                          <td><%= button_to 'Elimina', tour, method: :delete,class:'btn btn-outline-danger ', data: {confirm: "Sei sicuro di voler eliminare questo tour?"}  %></td>
                          </div>
                          </div>  
                        
               
            </div>
        </div>
        <%end%>
        <%end%>
        <!-- Sidebar-->
        
        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</section>

                  
</div>
<main class="ui two column doubling stackable grid container">
<h1>My Next Tours</h1>

<section class="column">
<div class="container pb-5 mt-n2 mt-md-n3">
<div class="row">
<% Tour.all.each do |tour|%>
<% tour.memberships.each do |member|%>
<%if member.user_id== current_user.id%>


<div class="d-sm-flex justify-content-between my-4">
                <div class="media d-block d-sm-flex text-center text-sm-left">
                    <div class="cart-item-thumb mx-auto mr-sm-4">
                    <div class="account-settings">
                  <div class="card-body">
                  <div class="user-profile">
                  <div class="user-avatar" class= "img-circular">
                    <%=image_tag(tour.user.avatar_thumbnail) %>
                    </div>
                    <%= link_to 'Show Trip', tour,class:"btn btn-outline-primary" %>
                    </div>
                    </div>
                    </div>
                    
                    </div>
                    <div class="media-body pt-3">
                        <h3 class="product-card-title font-weight-semibold border-0 pb-0"><%= link_to  tour.user.username, user_path(tour.user) %></h3>
                        <div class="font-size-sm"><span class="text-muted mr-2">Start:</span>
                        <%= tour.Data %>|<%= tour.Partenza %></div>
                        <div class="font-size-sm"><span class="text-muted mr-2">End:</span>
                        <%= tour.enddate %>|<%= tour.destinazione %></div>
                        <div class="font-size-sm"><span class="text-muted mr-2">Descrizione:</span>
                        <%= tour.description %></div>
                        <div class="font-size-sm"><span class="text-muted mr-2">Veichle:</span><%= tour.Mezzo_Di_Trasporto %></div>
                        <div class="font-size-sm"><span class="text-muted mr-2">Passengers:</span>  <%tour.memberships.count%>/<%= tour.Posti_Disponibili %></div>
                    </div>
                </div>
                <div class="pt-2 pt-sm-0 pl-sm-3 mx-auto mx-sm-0 text-center text-sm-left" style="max-width: 10rem;">
                    
                    
                        
               
            </div>
        </div>
        <%end%>
        <%end%>
        <%end%>
        <!-- Sidebar-->
        
        
                        </div>
                    </div>
                </div>
            </div>
        </div>

</div>
</div>
</section>
</main>
<%end%>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Auto/Moto Touring App',root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
       
        <li class="nav-item">
          <%= link_to "Chi Siamo", home_about_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
         <%= link_to "Statistiche", home_stat_path, class:"nav-link active"%>
        </li>

        <% if user_signed_in? %>
        <li class="nav-item">
         <%= link_to "HOME", tours_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
         <%= link_to "Profile", user_path(current_user), class:"nav-link active"%>
        </li>
        <li class="nav-item">
         <%= link_to "My Tours", home_ALL_path, class:"nav-link active"%>
        </li>
        
        <li class="nav-item">
         <%= link_to "all profile", users_index_path, class:"nav-link active"%>
        </li>
        
        
        <li class="nav-item">
         <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link active"%>
        </li>
         <li class="nav-item" >
         <%= button_to "Sign Out", destroy_user_session_path, method: :delete,class: 'btn btn-dark navbar-btn btn-sm' %>
        </li>
        
        
        <div class="text-warning">Logged in as <%= current_user.email%> </div>
        

        <% else %>

        <li class="nav-item">
         <%= link_to "Sign Up", new_user_registration_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
         <%= link_to "Sign In", new_user_session_path, class:"nav-link active"%>
        </li>

        <% end %>
       
        
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us...</h1>

app/views/home/index.html.erb
<h1>Auto/Moto Touring</h1>

app/views/home/stat.html.erb
<h1>Statistiche</h1>