config/routes.rb
Rails.application.routes.draw do
 
  
  
  get 'users/index'
  devise_for :users, :path_prefix => 'id' ,
  :controllers => { :omniauth_callbacks => 
  "users/omniauth_callbacks" }

  
  resources :users, :only =>[:show]


  
  resources :tours do
      member do
        get 'join'
        delete :remove_from_tour
      end
    resources :stops
    resources :comments
    resources :memberships
  end
  #root 'tours#index'
  root 'tours#index'
  get 'home/index'
  get 'home/about'
  get 'home/stat'
  get 'home/ALL'
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  
  
  
  get 'invitations/create'
  get 'invitations/destroy'
  get 'invitations/update'

 

  
 
 
 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tour.rb
class Tour < ApplicationRecord
    belongs_to :user
    
    has_many :stops, dependent: :destroy
    has_many :comments

    has_many :memberships 
    has_many :users, :through => :memberships,dependent: :destroy
    
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: %i[ show edit update destroy]
  before_action :authenticate_user!,except: [:home_about, :home_index, :home_stat]
  before_action :correct_user, only: [:edit, :update, :destroy]


  # GET /tours or /tours.json
  def index
    @tours = Tour.all
    if params[:search_by_autista] && params[:search_by_autista] != ""
      @tours = @tours.where("Autista like ?", 
      "%#{params[:search_by_autista]}%")
    end
    if params[:search_by_partenza] && params[:search_by_partenza] != ""
      @tours = @tours.where("Partenza like ?", 
      "%#{params[:search_by_partenza]}%")
    end
    if params[:search_by_destinazione] && params[:search_by_destinazione] != ""
      @tours = @tours.where("destinazione like ?", 
      "%#{params[:search_by_destinazione]}%")
    end
    if params[:search_by_data] && params[:search_by_data] != ""
      @tours = @tours.where("data like ?", 
      "%#{params[:search_by_data]}%")
    end
  end
  
 
  # GET /tours/1 or /tours/1.json
  def show
    @comments = @tour.comments.all
    @comment = @tour.comments.build
  end
 

  # GET /tours/new
  def new
    #@tour = Tour.new
    @tour = current_user.tours.build

  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours or /tours.json
  def create
    #@tour = Tour.new(tour_params)
    @tour = current_user.tours.build(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: "Tour was successfully created." }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1 or /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: "Tour was successfully updated." }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1 or /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: "Tour was successfully destroyed." }
      format.json { head :no_content }
    end
  end



def join
  @tour = Tour.find(params[:id])
  @m = @tour.memberships.build(:user_id => current_user.id)
  respond_to do |format|
    if @m.save
      format.html { redirect_to(@tour, :notice => 'You have joined this Tour.') }
      format.xml  { head :ok }
    else
      format.html { redirect_to(@tour, :notice => 'Join error.') }
      format.xml  { render :xml => @tour.errors, :status => :unprocessable_entity }
    end
  end
end

def remove_from_tour
  @tour = Tour.find(params[:id]) #can do that in before_filter
  @membership = @tour.memberships.find_by(tour_id: params[:id], user_id: current_user.id)
  if @membership
    @membership.destroy
    flash[:notice] = "Removed membership."
    redirect_to @tour
  else
    flash[:notice] = "No membership Found."
    redirect_to @tour
  end
  
end


def correct_user
  @tour.user = current_user
  redirect_to tours_path, notice:"Not Autorized To Edit This Tour" if @tour.nil?
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

 

    # Only allow a list of trusted parameters through.
    def tour_params
      params.require(:tour).permit(:Autista, :Mezzo_Di_Trasporto, :Data, :Partenza, :destinazione, :durata, :Posti_Disponibili,:user_id)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= form_with(model: tour) do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
        <% tour.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field form-group">
    
    <%= form.text_field :Autista, class:"form-control",value: current_user.username ,type: :hidden%>
  </div>
<br/>
  <div class="field form-group">
    <%= form.text_field :Mezzo_Di_Trasporto, class:"form-control",value: current_user.vehicle ,type: :hidden%>
  </div>
<br/>
  <div class="field form-group">
    <%= form.label :Start_Data %>
    <%= form.date_select :Data, class:"form-control",placeholder:"Start Date" %>
  </div>
<br/>
<div class="field form-group">
    <%= form.label :End_Data %>
    <%= form.date_select :enddate, class:"form-control",placeholder:"End Date" %>
  </div>
<br/>

  <div class="field form-group">
   
    <%= form.text_field :Partenza, class:"form-control",placeholder:"Partenza",id:"from"%>
  </div>
<br/>
  <div class="field form-group">
   
    <%= form.text_field :destinazione, class:"form-control",placeholder:"Destinazione",id:"to" %>
  </div>
<br/>
<div class="field form-group">
   
    <%= form.text_field :description, class:"form-control",placeholder:"Description",id:"description" %>
  </div>
<br/>
  <div class="field form-group">
   
    <%= form.number_field :Posti_Disponibili, class:"form-control",placeholder:"Posti Disponibili" %>
  </div>
  <br/>
 
  <div class="field form-group">
   
    <%= form.number_field :user_id, id: :tour_user_id, class:"form-control",value: current_user.id ,type: :hidden %>
  </div>
  


<br/>
 
<script>


var input1 = document.getElementById("from");
var autocomplete1 = new google.maps.places.Autocomplete(input1);

var input2 = document.getElementById("to");
var autocomplete2 = new google.maps.places.Autocomplete(input2);
</script>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Modifica Tour</h1>

<%= render 'form', tour: @tour %>

app/views/tours/index.html.erb
<%if user_signed_in?%>
<% if @tours == [] || @tours == nil %>
    <main class="ui raised very padded text container segment">
        <h1 class="ui header">No Results Found</h1>
        <a class="ui mini positive button" href="/tours/new">Start your own?</a>
        <a class="ui mini teal button" href="/home/about">About Us</a>
    </main>
    <% else %>                     
    </div>
  
<br>




<main class="ui two column doubling stackable grid container">
<section class="column">
<div class="container pb-5 mt-n2 mt-md-n3">
    <div class="row">
    <% @tours.each do |tour| %>
        
            
            <!-- Item-->
            <!-- Item-->
            <!-- Item-->
            
            <div class="d-sm-flex justify-content-between my-4">
                <div class="media d-block d-sm-flex text-center text-sm-left">
                    <div class="cart-item-thumb mx-auto mr-sm-4">
                    <div class="account-settings">
                  <div class="card-body">
                  <div class="user-profile">
                  <div class="user-avatar" class= "img-circular">
                    <%=image_tag(tour.user.avatar_thumbnail) %>
                    </div>
                    <%= link_to 'Show Trip', tour,class:"btn btn-outline-primary" %>
                    </div>
                    </div>
                    </div>
                    
                    </div>
                    <div class="media-body pt-3">
                        <h3 class="product-card-title font-weight-semibold border-0 pb-0"><%= link_to  tour.user.username, user_path(tour.user) %></h3>
                        <div class="font-size-sm"><span class="text-muted mr-2">Start:</span>
                        <%= tour.Data %>|<%= tour.Partenza %></div>
                        <div class="font-size-sm"><span class="text-muted mr-2">End:</span>
                        <%= tour.enddate %>|<%= tour.destinazione %></div>
                        <div class="font-size-sm"><span class="text-muted mr-2">Descrizione:</span>
                        <%= tour.description %></div>
                        <div class="font-size-sm"><span class="text-muted mr-2">Veichle:</span><%= tour.Mezzo_Di_Trasporto %></div>
                        <div class="font-size-sm"><span class="text-muted mr-2">Passengers:</span>  <%=tour.memberships.count%>/<%= tour.Posti_Disponibili %></div>
                    </div>
                </div>
                <div class="pt-2 pt-sm-0 pl-sm-3 mx-auto mx-sm-0 text-center text-sm-left" style="max-width: 10rem;">
                    
                            
                        
               
            </div>
        </div>
        <%end%>
        <!-- Sidebar-->
        
        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</section>

                   <section class="column">
                <div class="ui teal segment">
                    <div class="ui basic segment">
                        <h4 class="ui header">Search by:</h4>
                        
                        <form>
<%= form_tag "/tours", method: "GET" do %>
  <div class="form-row">
    <div class="form-group" >
    
      <%= label_tag :search_by_autista %>
      <%= text_field_tag :search_by_autista, params[:search_by_autista], class:"form-control" %>
     
    </div>
    <div class="form-group">
      
      <%= label_tag :search_by_partenza %>
      <%= text_field_tag :search_by_partenza, params[:search_by_partenza], class:"form-control"%>

    </div>

    <div class="form-group">
      
      <%= label_tag :search_by_destinazione %>
      <%= text_field_tag :search_by_destinazione, params[:search_by_destinazione], class:"form-control"%>

    </div>
    <div class="form-group">
      
      <%= label_tag :search_by_data %>
      <%= date_field_tag :search_by_data, params[:search_by_data], class:"form-control"%>

    </div>



  </div>
  <br>
  <div class="ui action input">
  <div class="form-group">
  <%=submit_tag "Search",class:"btn btn-primary btn-lg" %>
  </div>
                                   
  </div>
  
  <% end %>
</form>

                    
                </div>
</section>
</div>
<%end%>
<%else%>

<%= link_to "Sign In", new_user_session_path, class:"nav-link active"%>


<%end%>

app/views/tours/new.html.erb
<h1>Aggiungi Nuovo Tour</h1>

<%= render 'form', tour: @tour %>
<br/>
<%= link_to 'Back', tours_path,class:"btn btn-dark" %>

app/views/tours/show.html.erb
<main class="ui two column doubling stackable grid container">
    <div class="column">
        <div class="ui basic segment">
        
            <h1 class="display-4" class="ui header">
            
               <%= @tour.Autista %>
                
            
        </div>
        <div class="ui raised padded text segment">
            <h3>Partenza</h3>
            <p>
                <%= @tour.Partenza %>
            </p>
            <h3>Destinazione</h3>
            <p>
                <%= @tour.destinazione %>
            </p>
            <h3>Start Date:</h3>
            <p>
                <%= @tour.Data %>
            </p>
            <h3>End Date:</h3>
            <p>
                <%= @tour.enddate %>
            </p>
            <h3>Mezzo Di Trasporto:</h3>
            <p>
                <%= @tour.Mezzo_Di_Trasporto %>
            </p>
            <h3>Description:</h3>
            <p>
                <%= @tour.description %>
            </p>
            <div class="d-flex flex-row-reverse">
            <%if current_user!= @tour.user%>
            <%if @tour.memberships.count<@tour.Posti_Disponibili %>
                    
                    <div class="p-2"><%=link_to 'Join Tour', join_tour_path(@tour),class:"btn btn-outline-success" %></div>
                    <%Membership.all.each do |member|%>
                    <%if member.tour_id ==@tour.id && member.user_id == current_user.id%>
                    <div class="p-2"><%= button_to "Leave Tour", remove_from_tour_tour_path(@tour),class:"btn btn-danger", :method => :delete%></div>
                    
                    <%end%>
                    
                    <%end%>
                    
             <%else%>

            <button type="button" class="btn btn-outline-danger" disabled>COMPLETE</button>
            <%Membership.all.each do |member|%>
                    <%if member.tour_id ==@tour.id && member.user_id == current_user.id%>
                    <div class="p-2"><%= button_to "Leave Tour", remove_from_tour_tour_path(@tour),class:"btn btn-danger", :method => :delete%></div>
                    <%end%>
                    <%end%>
                    <%end%>
                    <%end%>

        </div>
        </div>
        
        <div class="ui basic segment">
            <h4 class="ui header">Stops:</h4>
            <div class="ui two column doubling stackable grid container">
                 <% @tour.stops.each do |stop| %>
                    <span class="column">
                        <div class="ui attached segment">
                           <%= link_to stop.address, tour_stop_path(@tour, stop) %>
                        </div>
                    </span>
                    <% end %>
                     
            </div>
        </div>
        <div class="ui floated basic segment">
            <h4>Passengers:</h4>
            <div class="d-flex">
            <% Membership.all.each do |member| %>
              <tr>
              <%if member.tour_id==@tour.id%>
              
                <div class="p-2">
                <div class="card" style="width: 12rem; ">
                <div class="card-header">
                    <%= link_to  member.user.username, user_path(member.user) %>
                    </div>
                <h5 class="card-title"></h5>
                <div class="card-body">
                
                <div class="account-settings">
                <div class="user-profile">
                  <div class="user-avatar" class= "img-circular">
                <h6 class="card-subtitle mb-2 text-muted"><%=image_tag(member.user.avatar_thumbnail) %></h6>
                </div>
                </div>
                </div>
                
    
                </div>
                </div>
                </div>
                
               
              <%end%>
            <% end %>

            </div>
            
           



            
            
           

        </div>
    </div>
    
        <div class="column">
            <div class="ui basic segment"></div>
            
            </h1>
                <div class="ui segment">
                    <h3>Tragitto:</h3>
                    <script>
var directionsDisplay = new google.maps.DirectionsRenderer();
var directionsService = new google.maps.DirectionsService();
var renderOptions = { draggable: true };

function calcRoute() {
    var waypoints = [];
    '<%@tour.stops.each do |stop|%>'
        waypoints.push(
        {
        location: new google.maps.LatLng('<%=stop.latitude%>', '<%=stop.longitude%>')
        }
        );
      
    '<%end%>'
    
  var infowindow = new google.maps.InfoWindow();
    var request = {
        origin:      "<%=@tour.Partenza%>",
        destination: "<%=@tour.destinazione%>",
        waypoints: waypoints,
        travelMode:  google.maps.TravelMode.DRIVING,
        unitSystem: google.maps.UnitSystem.IMPERIAL
    };
    
    directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {

            directionsDisplay.setDirections(response);
        }
    });
}

calcRoute();

</script>
<div style='width: 800px;'>
  <div id="map" style='width: 500px; height: 400px;'></div>
  </div>
<script>

handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    directionsDisplay.setMap(handler.getMap());
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(15);
});


</script>
 </div>
               
                    <div class="ui segment">
                    <h3>Posti a Disposizione:</h3>
            <p>
                <%= @tour.Posti_Disponibili %>
            </p>
            <h3>Partecipanti:</h3>
            <p>
                <%= @tour.memberships.count %>
            </p>
                </div>
                       
                        



 

                           
<hr class="my-4">
  
  <p class="lead">

  <%if @tour.user==current_user%>
    <%= link_to 'Edit', edit_tour_path(@tour),class:"btn btn-outline-warning" %> 
    <%= link_to 'Add Stop', new_tour_stop_path(@tour),class:"btn btn-outline-info" %> 
    
  
  <% end %>
  
  
  </p>
       
    

  
    
    
  </div>

  
</div>
                             
                               
                              
  </main>
      
  
       